# Generated by Django 4.2.19 on 2025-03-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0013_create_industry_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'job_positions',
            },
        ),
    ]
