# Generated by Django 4.2.19 on 2025-03-20 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0014_create_job_positions_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='placemate_app.user')),
                ('name', models.CharField(max_length=255)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('company_size', models.PositiveSmallIntegerField(choices=[(0, '1-10 employees'), (1, '11-50 employees'), (2, '51-250 employees'), (3, '251-1000 employees'), (4, '1001+ employees')], default=1)),
                ('company_type', models.PositiveSmallIntegerField(choices=[(0, 'Private Limited Company'), (1, 'Public Limited Company'), (2, 'Government Organization'), (3, 'Non-Profit Organization'), (4, 'Startup'), (5, 'Cooperative'), (6, 'Multinational Corporation'), (7, 'Educational Institution')], default=0)),
                ('contact_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='placemate_app.jobposition')),
                ('headquater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='placemate_app.city')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='placemate_app.industry')),
            ],
            options={
                'db_table': 'companies',
            },
        ),
    ]
