# Generated by Django 4.2.19 on 2025-03-20 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0015_create_companies_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='placemate_app.user')),
                ('enrollment', models.PositiveIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('joining_year', models.PositiveIntegerField()),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('profile', models.CharField(blank=True, max_length=255, null=True)),
                ('placement_status', models.PositiveSmallIntegerField(choices=[(0, 'Not Placed'), (1, 'Placed'), (2, 'Internship'), (3, 'Job Offer Received')], default=0)),
                ('graduation_status', models.CharField(choices=[('Pursuing', 'Pursuing'), ('Completed', 'Completed'), ('Dropped Out', 'Dropped Out')], default='Pursuing', max_length=20)),
                ('package', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='placemate_app.city')),
                ('company_placedIn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placed_students', to='placemate_app.company')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='placemate_app.course')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
