# Generated by Django 4.2.19 on 2025-03-20 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0017_create_skills_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=20)),
                ('job_mode', models.CharField(choices=[('Offline', 'Offline'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('application_deadline', models.DateTimeField()),
                ('salary_package_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_package_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bond', models.CharField(blank=True, max_length=100, null=True)),
                ('minimum_cgpa', models.FloatField(blank=True, null=True)),
                ('job_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Filled', 'Filled')], default='Open', max_length=20)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.company')),
                ('job_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='placemate_app.jobposition')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
