# Generated by Django 4.2.19 on 2025-03-20 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0018_create_jobs_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.course')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.job')),
            ],
            options={
                'db_table': 'job_courses',
                'unique_together': {('job', 'course')},
            },
        ),
    ]
