# Generated by Django 4.2.19 on 2025-03-20 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0019_create_job_courses_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.city')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.job')),
            ],
            options={
                'db_table': 'job_locations',
                'unique_together': {('job', 'city')},
            },
        ),
    ]
