# Generated by Django 4.2.19 on 2025-03-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0022_create_job_applications_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('interview_type', models.CharField(choices=[('HR', 'HR'), ('Technical', 'Technical'), ('Group Discussion', 'Group Discussion'), ('Aptitude Test', 'Aptitude Test')], max_length=20)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=15)),
                ('result', models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('On-Hold', 'On-Hold')], max_length=10, null=True)),
                ('interview_date', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.jobapplication')),
            ],
            options={
                'db_table': 'interviews',
            },
        ),
    ]
