# Generated by Django 4.2.19 on 2025-03-20 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0025_create_drive_companies_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.placementdrive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.student')),
            ],
            options={
                'db_table': 'drive_students',
                'unique_together': {('drive', 'student')},
            },
        ),
    ]
