# Generated by Django 4.2.19 on 2025-04-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0028_create_notifications_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='application_deadline',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_position',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_status',
        ),
    ]
