# Generated by Django 4.2.19 on 2025-04-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0029_remove_jobs_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drivestudent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='drivestudent',
            name='drive',
        ),
        migrations.RemoveField(
            model_name='drivestudent',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='placementoffer',
            unique_together={('student', 'job')},
        ),
        migrations.DeleteModel(
            name='DriveCompany',
        ),
        migrations.DeleteModel(
            name='DriveStudent',
        ),
        migrations.RemoveField(
            model_name='placementoffer',
            name='drive',
        ),
    ]
