# Generated by Django 4.2.19 on 2025-04-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0030_remove_unnessary_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDrive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('drive_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('registration_start_date', models.DateField()),
                ('registration_end_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.company')),
            ],
            options={
                'db_table': 'comapany_drives',
            },
        ),
        migrations.DeleteModel(
            name='PlacementDrive',
        ),
    ]
