# Generated by Django 4.2.19 on 2025-04-01 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0031_create_company_drives_tables'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placementoffer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('A', 'A'), ('A1', 'A1')], default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='job',
            name='diploma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tenth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='twelfth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='undergraduate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='placemate_app.companydrive'),
        ),
        migrations.AddField(
            model_name='placementoffer',
            name='drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='placemate_app.companydrive'),
        ),
        migrations.AlterUniqueTogether(
            name='placementoffer',
            unique_together={('student', 'job', 'drive')},
        ),
    ]
