# Generated by Django 4.2.19 on 2025-04-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0032_added_some_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDriveJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.companydrive')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.job')),
            ],
            options={
                'db_table': 'company_drive_jobs',
                'unique_together': {('company_drive', 'job')},
            },
        ),
    ]
