# Generated by Django 4.2.19 on 2025-04-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0034_changes_in_company_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Reviewed', 'Reviewed'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Applied', max_length=20)),
                ('resume_link', models.CharField(max_length=500)),
                ('drive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='placemate_app.companydrive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.student')),
            ],
            options={
                'db_table': 'drive_applications',
            },
        ),
        migrations.AlterField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.driveapplication'),
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
