# Generated by Django 4.2.19 on 2025-04-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0035_rename_jobApplications_to_drive_applications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='twelfth',
            new_name='twelth',
        ),
    ]
