# Generated by Django 4.2.19 on 2025-04-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0036_rename_field_twelth_in_jobs_due_to_typo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydrive',
            name='registration_end_date',
        ),
        migrations.RemoveField(
            model_name='companydrive',
            name='registration_start_date',
        ),
        migrations.AlterField(
            model_name='companydrive',
            name='end_date',
            field=models.DateTimeField(default='2025-04-08 10:30:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companydrive',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
