# Generated by Django 4.2.19 on 2025-04-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0038_add_timestamp_in_every_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='years',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
