# Generated by Django 4.2.19 on 2025-04-09 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0039_added_course_year_in_courses_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.course')),
            ],
            options={
                'db_table': 'drive_courses',
            },
        ),
        migrations.CreateModel(
            name='DriveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.city')),
            ],
            options={
                'db_table': 'drive_locations',
            },
        ),
        migrations.CreateModel(
            name='DriveSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'drive_skills',
            },
        ),
        migrations.AlterUniqueTogether(
            name='joblocation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='joblocation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='joblocation',
            name='job',
        ),
        migrations.AlterUniqueTogether(
            name='jobskill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobskill',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='job',
            name='bond',
        ),
        migrations.RemoveField(
            model_name='job',
            name='diploma',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_mode',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='minimum_cgpa',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_package_max',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_package_min',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tenth',
        ),
        migrations.RemoveField(
            model_name='job',
            name='twelth',
        ),
        migrations.RemoveField(
            model_name='job',
            name='undergraduate',
        ),
        migrations.AddField(
            model_name='companydrive',
            name='bond',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companydrive',
            name='diploma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydrive',
            name='job_mode',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default='Offline', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydrive',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Contract', 'Contract')], default='Full-time', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydrive',
            name='minimum_cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydrive',
            name='pg_package_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydrive',
            name='pg_package_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydrive',
            name='stipend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='companydrive',
            name='tenth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydrive',
            name='twelth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydrive',
            name='ug_package_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydrive',
            name='ug_package_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydrive',
            name='undergraduate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='JobCourses',
        ),
        migrations.DeleteModel(
            name='JobLocation',
        ),
        migrations.DeleteModel(
            name='JobSkill',
        ),
        migrations.AddField(
            model_name='driveskill',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.companydrive'),
        ),
        migrations.AddField(
            model_name='driveskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.skill'),
        ),
        migrations.AddField(
            model_name='drivelocation',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.companydrive'),
        ),
        migrations.AddField(
            model_name='drivecourses',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.companydrive'),
        ),
        migrations.AlterUniqueTogether(
            name='driveskill',
            unique_together={('drive', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='drivelocation',
            unique_together={('drive', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='drivecourses',
            unique_together={('drive', 'course')},
        ),
    ]
