# Generated by Django 4.2.19 on 2025-04-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0040_change_mapper_tables_from_jobs_to_drives'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
