# Generated by Django 4.2.19 on 2025-04-11 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0042_remove_job_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementoffer',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='placemate_app.companydrivejobs'),
        ),
    ]
