# Generated by Django 4.2.19 on 2025-04-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0044_typo_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='backlog',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
