# Generated by Django 4.2.19 on 2025-04-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0045_student_backlog_student_tenth_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Reviewed', 'Reviewed'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
    ]
