# Generated by Django 4.2.19 on 2025-04-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0046_alter_driveapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Reviewed', 'Reviewed'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Applied', max_length=20),
        ),
    ]
