# Generated by Django 4.2.19 on 2025-04-19 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0047_alter_driveapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementoffer',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='placemate_app.driveapplication'),
        ),
    ]
