# Generated by Django 4.2.19 on 2025-04-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0048_alter_placementoffer_job'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placementoffer',
            unique_together={('student', 'job')},
        ),
    ]
