# Generated by Django 4.2.19 on 2025-05-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placemate_app", "0049_alter_placementoffer_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="placementcellmember",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
