# Generated by Django 4.2.19 on 2025-03-19 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placemate_app', '0004_create_Role_Permission_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placemate_app.user')),
            ],
            options={
                'db_table': 'User_roles'
            },
        ),
    ]
